#!/usr/bin/env bash 
# https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/

user_name=$1
repo_name=$2
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1
test -z $user_name && echo "github username required." 1>&2 && exit 1
curl -u "$1":"$GITHUB_SECRET" https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"

# use direnv to keep sourced secrets bound to the local working directory.
