#!/usr/bin/env bash 
# https://help.github.com/articles/adding-an-existing-project-to-github-using-the-command-line/

repo_name=$1
test -z $repo_name && echo "Repo name required." 1>&2 && exit 1
test -z $GITHUB_USER && echo "github username required." 1>&2 && exit 1
curl -u "$GITHUB_USER":"$GITHUB_SECRET" https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"

# use direnv to keep sourced secrets bound to the local working directory.
